### ISSUE TITLE
Issue on page /collections/naturalis_biodiversity_center.html

### ISSUE THREAD

**Issue by larsgw** [visiblenature/visiblenature.github.io#1] opened 2023-11-16 10:10 UTC
All species in a group link to the same page (e.g. http://visiblenatu.re/inSuriname/taxa/uvigerina_hispidocostata.html for animals).

**Comment by andrawaag** [comment] 2023-11-16 11:16
@larsgw Thanks for the catch. This was caused by a early instantiation of a taxon variable in the building script. It is now fixed

**Closed as completed by andrawaag** 2023-11-16 11:16 UTC
